---
- name: Add the liferay group
  group:
    name: "{{ liferay_group }}"
    state: present

- name: Add the liferay user
  user:
    name: "{{ liferay_user }}"
    password_lock: true
    shell: /bin/bash
    append: true

- name: Check to see if already installed
  stat:
    path: "{{ liferay_dest }}"
  register: stat_liferay_dest

- name: Set new install flag
  set_fact:
    new_liferay_dest: true
  when:
    - stat_liferay_dest.stat.exists is defined
    - not stat_liferay_dest.stat.exists

- name: Ensure dest exists
  file:
    path: "{{ liferay_dest }}"
    owner: "{{ liferay_user }}"
    group: "{{ liferay_group }}"
    state: directory
    mode: 0700
    recurse: true
  when: new_liferay_dest is defined

- name: Get the Liferay Bundle
  unarchive:
    src: "{{ liferay_url }}"
    remote_src: true
    dest: "{{ liferay_dest }}"
    owner: "{{ liferay_user }}"
    group: "{{ liferay_group }}"
    mode: 0755
  register: install_liferay
  until: install_liferay is succeeded
  retries: 3
  when: new_liferay_dest is defined

- name: configure liferay instance - portal-ext.properties
  template:
    src: portal-ext.properties.j2
    dest: "{{ liferay_home }}/portal-ext.properties"

- name: configure liferay portal search osgi config
  template:
    src: com.liferay.portal.search.elasticsearch6.configuration.ElasticsearchConfiguration.config.j2
    dest: "{{ liferay_home }}/osgi/configs/com.liferay.portal.search.elasticsearch6.configuration.ElasticsearchConfiguration.config"

- name: configure liferay document store osgi config
  template:
    src: com.liferay.portal.store.file.system.configuration.AdvancedFileSystemStoreConfiguration.cfg.j2
    dest: "{{ liferay_home }}/osgi/configs/com.liferay.portal.store.file.system.configuration.AdvancedFileSystemStoreConfiguration.cfg"


# Run life service
# ${LIFERAY_HOME}/tomcat/bin/catalina.sh run
- name: create liferay service instance
  import_role:
    name: micko920.role_createservice
  vars:
    service_list:
      - name: "{{ liferay_service_name }}"
        description: "{{ liferay_service_description }}"
        start_command: "{{ liferay_tomcat_home }}/bin/startup.sh"
        stop_command: "{{ liferay_tomcat_home }}/bin/shutdown.sh"
        user_name: "{{ liferay_user }}"
        group_name: "{{ liferay_group }}"
        type: "forking"
        after: "syslog.target network.target"
