---
- include_tasks: is_systemd.yml

# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: initialize.yml

- name: Set final state and enable liferay instance
  service:
    name: "{{ liferay_service_name }}"
    state: "{{ liferay_final_state }}"
    enabled: yes
