---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: molecule/requirements.yml

driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: homelab-systemd-local
    image: ${MOLECULE_DOCKER_IMAGE:-"homelab-systemd:local"}
    command: "/sbin/init"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    exposed_ports:
      - 8080/tcp
      - 8000/tcp
      - 11311/tcp
    published_ports:
      - 0.0.0.0:8080:8080/tcp
      - 0.0.0.0:8000:8000/tcp
      - 0.0.0.0:11311:11311/tcp
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: testinfra
  lint:
    name: flake8
